### ISSUE TITLE
Android Studio wrong key map

### ISSUE THREAD

**Issue by ndurell** [athiele/key-promoter-fork#18]
It appears that on the mac that the key promoter plugin mixes up the alt key with command key.
Any idea what causes this?
I'm asking here because it doesn't look like the old key promoter has been updated since 2012.
I'm also using Android studio btw...

**Comment by ndurell** [comment]
2.2 RC

**Comment by ndurell** [comment]
I'm using Mac OS X 10.5 keymap.

**Comment by ndurell** [comment]
<img width="295" alt="screen shot 2016-09-19 at 1 17 31 pm" src="https://cloud.githubusercontent.com/assets/653455/18641640/8d0896c0-7e6b-11e6-9452-ac805939810e.png">

**Comment by athiele** [comment]
You are right, this does not work for me as well. I just never noticed. Two insights:
* This only affects Alt+0 to Alt+9 for the tool windows, every other shortcut is displayed correctly
* I suspect the following code to be buggy: https://github.com/athiele/key-promoter-fork/blob/master/src/org/jetbrains/contest/keypromoter/KeyPromoter.java#L113-L118

**Comment by ndurell** [comment]
Ahh ok if it's just for those menu items I guess it's not that big a deal...

**Comment by athiele** [comment]
Fixed in 2.0.7. If you need this fix working on Android Studio 2.2 RC, you can cherry-pick https://github.com/athiele/key-promoter-fork/commit/4f3dc9a15e85f42069e30227e5ca03ca2e9c2724
from the tag 2.0.4 and build the plugin. Tell me in case you need help doing so.

Thanks for reporting - closing this issue for now
