### ISSUE TITLE
last version 2.0.7 is incompatible with Android Studio 2.2.3

### ISSUE THREAD

**Issue by zhenian** [athiele/key-promoter-fork#21]
rt

**Comment by athiele** [comment]
Hi, thanks for reporting! Android Studio 2.2.3 is based on IntelliJ 2016.1. As described in the README you need to install version 2.0.4 as IntelliJ introduced some breaking changes in 2016.2.

I hope that Android Studio will be upgraded soon so that the most recent version of the Key Promoter works there, too.
