### ISSUE TITLE
[feature request]: add setting for stop showing a dialog after a certain number of times?

### ISSUE THREAD

**Issue by Aracki** [athiele/key-promoter-fork#25]
It would be cool to add functionality to stop showing a dialog after a certain number of times that dialog has been shown (e.g. 10, 20, 50 times).

**For example**: _After the twentieth time I see the same dialog I will learn a new shortcut and I don't want to see dialog for that combo again._

**Comment by halirutan** [comment]
This was implemented. If you compile a recent version you should find it in settings. When you want to try Key Promoter X, which uses IntelliJ notifications instead of custom pop-ups, you will get more features, i.e. (see [the images here](https://github.com/halirutan/IntelliJ-Key-Promoter)

- automatically sorted hit list with formatting and icons
- no dialogues that force you to react, but only clickable notifications
- you can suppress individual buttons that you never want to see a tip for and a you see them in a "suppressed button list"
- on OSX menu entries (which are kind of special) are working as well

What you will loose:

- setting the color, time-out, etc for the notification since everything is implemented using the non-intrusive messaging system of IDEA itself

**Comment by Aracki** [comment]
Great rewritten plugin! Thanks! 👆
